name: Ubuntu-CI
on:
  push:
    branches: [master, qt6, 1.9-stable]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install qtbase5-dev libkf5syntaxhighlighting-dev
      - name: Build qtextpad
        run: |
          mkdir build && cd build
          cmake -DCMAKE_BUILD_TYPE=Debug -DCMAKE_INSTALL_PREFIX=$GITHUB_WORKSPACE/dist ..
          make -j2 && make install
