name: Win64-CI
on:
  push:
    branches: [master, qt6]
  pull_request:

jobs:
  build:
    runs-on: windows-2019
    name: "Windows-x64-Qt${{ matrix.cfg.qt_version }}"
    strategy:
      matrix:
        cfg:
          - { kf5_version: "5.94", kf5_fullver: "5.94.0", qt_version: "5.15.2",
              qt_modules: "", cmake_generator: "Visual Studio 16 2019",
              kf5_cmake_args: "", build_installer: "$true" }
          - { kf5_version: "5.94", kf5_fullver: "5.94.0", qt_version: "6.2.4",
              qt_modules: "qt5compat", cmake_generator: "Visual Studio 16 2019",
              kf5_cmake_args: "-DBUILD_WITH_QT6=ON", build_installer: "$false" }

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install Qt
        uses: jurplel/install-qt-action@v2
        with:
          arch: win64_msvc2019_64
          version: ${{ matrix.cfg.qt_version }}
          modules: ${{ matrix.cfg.qt_modules }}
      - name: Build Qt Libs
        run: |
          mkdir build_deps
          cd build_deps
          curl -LO https://download.kde.org/stable/frameworks/${{ matrix.cfg.kf5_version }}/extra-cmake-modules-${{ matrix.cfg.kf5_fullver }}.zip
          curl -LO https://download.kde.org/stable/frameworks/${{ matrix.cfg.kf5_version }}/syntax-highlighting-${{ matrix.cfg.kf5_fullver }}.zip
          cmake -E tar xf extra-cmake-modules-${{ matrix.cfg.kf5_fullver }}.zip
          cd extra-cmake-modules-${{ matrix.cfg.kf5_fullver }}
          mkdir build
          cd build
          cmake -G "${{ matrix.cfg.cmake_generator }}" -A x64 `
              "-DCMAKE_PREFIX_PATH=${Env:RUNNER_WORKSPACE}/Qt/${{ matrix.cfg.qt_version }}/msvc2019_64" `
              "-DCMAKE_INSTALL_PREFIX=${Env:RUNNER_WORKSPACE}/Qt/${{ matrix.cfg.qt_version }}/msvc2019_64" `
              -DCMAKE_BUILD_TYPE=Release ${{ matrix.cfg.kf5_cmake_args }} ..
          cmake --build . --config Release --target install
          cd ..\..
          cmake -E tar xf syntax-highlighting-${{ matrix.cfg.kf5_fullver }}.zip
          cd syntax-highlighting-${{ matrix.cfg.kf5_fullver }}
          mkdir build && cd build
          cmake -G "${{ matrix.cfg.cmake_generator }}" -A x64 `
              "-DCMAKE_PREFIX_PATH=${Env:RUNNER_WORKSPACE}/Qt/${{ matrix.cfg.qt_version }}/msvc2019_64" `
              "-DCMAKE_INSTALL_PREFIX=${Env:RUNNER_WORKSPACE}/Qt/${{ matrix.cfg.qt_version }}/msvc2019_64" `
              -DCMAKE_BUILD_TYPE=Release ${{ matrix.cfg.kf5_cmake_args }} ..
          cmake --build . --config Release
          cmake --build . --config Release --target install
      - name: Build qtextpad
        run: |
          mkdir build
          cd build
          cmake -G "${{ matrix.cfg.cmake_generator }}" -A x64 `
            "-DCMAKE_PREFIX_PATH=${Env:RUNNER_WORKSPACE}/Qt/${{ matrix.cfg.qt_version }}/msvc2019_64" `
            "-DCMAKE_INSTALL_PREFIX=${Env:GITHUB_WORKSPACE}/dist/qtextpad-win64" `
            -DCMAKE_BUILD_TYPE=Release ..
          cmake --build . --config Release
          cmake --build . --config Release --target install
      - name: Package qtextpad
        run: |
          $buildver = ((git describe --dirty) | Out-String).Trim()
          $buildver += "-qt" + "${{ matrix.cfg.qt_version }}"[0]
          $Env:VCINSTALLDIR = "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC"
          cd "${Env:GITHUB_WORKSPACE}\dist"
          windeployqt qtextpad-win64\qtextpad.exe --release --no-opengl-sw
          cmake -E copy "${Env:GITHUB_WORKSPACE}\COPYING" `
              "${Env:RUNNER_WORKSPACE}\Qt\${{ matrix.cfg.qt_version }}\msvc2019_64\bin\KF5SyntaxHighlighting.dll" `
              qtextpad-win64
          cmake -E copy_directory "${Env:RUNNER_WORKSPACE}\Qt\${{ matrix.cfg.qt_version }}\msvc2019_64\bin\data" `
              qtextpad-win64\data
          windeployqt qtextpad-win64\KF5SyntaxHighlighting.dll --release --no-opengl-sw

          # TODO: Use the Qt versions of the OpenSSL libs.  Depends on
          # https://github.com/jurplel/install-qt-action/issues/16
          cmake -E copy "C:\Program Files\OpenSSL\bin\libcrypto-1_1-x64.dll" `
              "C:\Program Files\OpenSSL\bin\libssl-1_1-x64.dll" `
              qtextpad-win64

          cmake -E tar cf "..\qtextpad-win64-${buildver}.zip" --format=zip qtextpad-win64
          cd ..\win32
          cmake -E tar xf "..\qtextpad-win64-${buildver}.zip"
          if (${{ matrix.cfg.build_installer }}) {
              iscc setup.iss
              cmake -E rename qtextpad-win64.exe "..\qtextpad-win64-${buildver}.exe"
          }
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: QTextPad-win64
          path: qtextpad-win64-*.*
